### ISSUE TITLE
stack trace - possibly related to encoding?

### ISSUE THREAD

**Issue by theandym** [sporkd/compass-html5-boilerplate#7]
I am experiencing the following issue when trying to integrate this with Rails 3. I did a search and turned up this conversation about a similar looking issue: http://groups.google.com/group/compass-users/browse_thread/thread/5ae9d0d49a491e04/bc5e2b9a7bfb96e8 . Not sure if there is any relation, but would appreciate any insight. 

```
/Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `require': no such file to load -- html-boilerplate (LoadError)
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `block in require'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `block in load_dependency'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:596:in `new_constants_in'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `load_dependency'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `require'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/data.rb:105:in `require'
from /Users/andy/units/app/config/compass.rb:2:in `parse_string'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/serialization.rb:41:in `eval'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/serialization.rb:41:in `parse_string'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/serialization.rb:35:in `block in _parse'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/serialization.rb:34:in `open'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/serialization.rb:34:in `_parse'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/serialization.rb:13:in `new_from_file'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/helpers.rb:39:in `configuration_for'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/helpers.rb:83:in `add_project_configuration'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/app_integration/rails.rb:39:in `initialize!'
from /Users/andy/units/app/config/initializers/compass.rb:3:in `<top (required)>'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:235:in `load'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:235:in `block in load'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `block in load_dependency'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:596:in `new_constants_in'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `load_dependency'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:235:in `load'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/engine.rb:201:in `block (2 levels) in <class:Engine>'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/engine.rb:200:in `each'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/engine.rb:200:in `block in <class:Engine>'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/initializable.rb:25:in `instance_exec'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/initializable.rb:25:in `run'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/initializable.rb:50:in `block in run_initializers'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/initializable.rb:49:in `each'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/initializable.rb:49:in `run_initializers'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/application.rb:134:in `initialize!'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/application.rb:77:in `method_missing'
from /Users/andy/units/app/config/environment.rb:5:in `<top (required)>'
from /Users/andy/units/app/config.ru:3:in `require'
from /Users/andy/units/app/config.ru:3:in `block in <main>'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/builder.rb:46:in `instance_eval'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/builder.rb:46:in `initialize'
from /Users/andy/units/app/config.ru:1:in `new'
from /Users/andy/units/app/config.ru:1:in `<main>'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/builder.rb:35:in `eval'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/builder.rb:35:in `parse_file'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/server.rb:162:in `app'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/server.rb:248:in `wrapped_app'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/server.rb:213:in `start'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/commands/server.rb:65:in `start'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/commands.rb:30:in `block in <top (required)>'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/commands.rb:27:in `tap'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/commands.rb:27:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'
```

**Comment by sporkd** [comment]
It looks to me like html5-boilerplate gem is not in your Gemfile.  Just add the following line in there somewhere and do a bundle install.

gem "html5-boilerplate"

Rails 3 needs this even if you already have the gem installed.

Peter

**Comment by theandym** [comment]
Still experiencing an issue after adding that to my Gemfile. I basically just have the default Gemfile with the following at the bottom:

```
gem "compass", ">= 0.10.6"
gem "html5-boilerplate"
```

Here is the updated stack trace:

```
/Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `require': no such file to load -- html-boilerplate (LoadError)
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `block in require'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `block in load_dependency'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:596:in `new_constants_in'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `load_dependency'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `require'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/data.rb:105:in `require'
from /Users/andy/units/app/config/compass.rb:2:in `parse_string'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/serialization.rb:41:in `eval'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/serialization.rb:41:in `parse_string'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/serialization.rb:35:in `block in _parse'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/serialization.rb:34:in `open'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/serialization.rb:34:in `_parse'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/serialization.rb:13:in `new_from_file'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/helpers.rb:39:in `configuration_for'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/configuration/helpers.rb:83:in `add_project_configuration'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.10.6/lib/compass/app_integration/rails.rb:39:in `initialize!'
from /Users/andy/units/app/config/initializers/compass.rb:3:in `<top (required)>'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:235:in `load'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:235:in `block in load'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `block in load_dependency'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:596:in `new_constants_in'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `load_dependency'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:235:in `load'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/engine.rb:201:in `block (2 levels) in <class:Engine>'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/engine.rb:200:in `each'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/engine.rb:200:in `block in <class:Engine>'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/initializable.rb:25:in `instance_exec'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/initializable.rb:25:in `run'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/initializable.rb:50:in `block in run_initializers'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/initializable.rb:49:in `each'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/initializable.rb:49:in `run_initializers'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/application.rb:134:in `initialize!'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/application.rb:77:in `method_missing'
from /Users/andy/units/app/config/environment.rb:5:in `<top (required)>'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `require'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `block in require'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `block in load_dependency'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:596:in `new_constants_in'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `load_dependency'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `require'
from /Users/andy/units/app/config.ru:3:in `block in <main>'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/builder.rb:46:in `instance_eval'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/builder.rb:46:in `initialize'
from /Users/andy/units/app/config.ru:1:in `new'
from /Users/andy/units/app/config.ru:1:in `<main>'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/builder.rb:35:in `eval'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/builder.rb:35:in `parse_file'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/server.rb:162:in `app'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/server.rb:248:in `wrapped_app'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/rack-1.2.1/lib/rack/server.rb:213:in `start'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/commands/server.rb:65:in `start'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/commands.rb:30:in `block in <top (required)>'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/commands.rb:27:in `tap'
from /Users/andy/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/commands.rb:27:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'
```

**Comment by theandym** [comment]
By the way, thank you for the quick response!

**Comment by sporkd** [comment]
Hmm, did you run bundle install (or bundle update) after adding that line?

Does running bundle check return successfully?

And make sure that line in your Gemfile is not being scoped to only one env (i.e. test).

If all else fails, post the contents of you Gemfile.lock, config/compass.rb and initializers/compass.rb up to a gist.

Peter

**Comment by theandym** [comment]
Yes, I did try both those, and took at look at the Gemfile to make sure nothing looked odd (to me at least). Here is a gist with the info you mentioned: https://gist.github.com/824367 . Thanks again for all the help.

**Comment by sporkd** [comment]
Not really sure.  That is the exact stack trace I get if I remove html5-boilerplate from my bundle.  Are you sure you are calling the right rails bin and the correct gemset?

Have you tried bundle exec rails server

If that doesn't fix, I'm guessing something else in your environment or rvm config.

Peter

**Comment by theandym** [comment]
Well after trying almost everything else (different rubies, reinstalling RVM, etc.) I checked it out on another system and it worked beautifully. So I then just nuked my local git repo, re-cloned from the server, setup compass-html5-boilerplate again, and it worked like a charm. I feel like and idiot. Sorry for bothering you, and thanks again for all the help!

**Comment by sporkd** [comment]
No worries.  Been there myself many times.  Glad you got it working.

Peter
